### ISSUE TITLE
Add binary sensors

### ISSUE THREAD

**Issue by gerard33** [ChristianKuehnel/bimmer_connected#17]
- [ ] Doors
- [ ] Windows
- [ ] Door lock state
- [ ] Parking lights
- [ ] Condition based services
- [ ] Control messages
- [ ] Charging
- [ ] Connector status

You can assign this to me. I will rewrite my existing binary sensor component to work with your bimmer connected module.

```py
SENSOR_TYPES = {
    'doors_closed': ['Doors', 'opening'],
    'windows_closed': ['Windows', 'opening'],
    'door_lock_state': ['Door lock state', 'safety'],
    'lights_parking': ['Parking lights', 'light'],
    'condition_based_services': ['Condition based services', 'problem'],
    'check_control_messages': ['Control messages', 'problem']
}

SENSOR_TYPES_ELEC = {
    'charging_status': ['Charging', 'power'],       # CHARGINGACTIVE, CHARGINGENDED # attributes: lastChargingEndReason, lastChargingEndResult
    'connectorStatus': ['Connector status', 'plug']
}

CODE_TO_SERVICE_NAME = {
    '00001': 'motor_oil',
    '00003': 'brake_fluid',
    '00017': 'vehicle_inspection',  # from BMW i3
    '00100': 'car_check',
    '00032': 'vehicle_inspection'   # from BMW X1
}
```

**Comment by ChristianKuehnel** [comment]
Hi @gerard33,

yes that makes sense. 

FYI: The decorator `@backend_parameter` is just a convenient way to handling the errors around parsing the parameters.

**Comment by gerard33** [comment]
@ChristianKuehnel, I have started with the doors, windows and lock state but need some help so I can understand your module correctly. The code of the binary sensor script is added below.

1. How can I show the `device_state_attributes` correct like in the attached picture from my old setup?
I have used `for lid in vehicle_state.lids:` but can't get that data to show correct as dict in the return.

2. The status of the binary sensors are not shown correctly. For example the door lock state is shown as False/True however that should be Safe/Unsafe. I am using the device_class for this. In my old version I used `def is_on(self)` for the state, but can't get that to work correctly. Any ideas how to fix this?

3. I also get the following errors in the log:
```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/usr/src/app/homeassistant/helpers/entity.py", line 196, in async_update_ha_state
    "No entity id specified for entity {}".format(self.name))
homeassistant.exceptions.NoEntitySpecifiedError: No entity id specified for entity Mileage
```
Old setup
![untitled-2](https://user-images.githubusercontent.com/11230573/36358574-d5625612-1510-11e8-9043-ba0d0de9a547.png)

New setup
![screenshot_1](https://user-images.githubusercontent.com/11230573/36358619-87072dd4-1511-11e8-92c7-5d1f021a40b7.png)

The code for the binary sensor is as follows (using it as a custom component):
```py
"""
Reads vehicle status from BMW connected drive portal.

For more details about this platform, please refer to the documentation at
https://home-assistant.io/components/binary_sensor.bmw_connected_drive/
"""
import logging
import asyncio

from custom_components.bmw_connected_drive import DOMAIN as BMW_DOMAIN
from homeassistant.helpers.entity import Entity
from homeassistant.components.binary_sensor import (
     BinarySensorDevice, DEVICE_CLASSES_SCHEMA)

DEPENDENCIES = ['bmw_connected_drive']

_LOGGER = logging.getLogger(__name__)

SENSOR_TYPES = {
    'all_lids_closed': ['Doors', 'opening'],
    'all_windows_closed': ['Windows', 'opening'],
    'door_lock_state': ['Door lock state', 'safety']
}


def setup_platform(hass, config, add_devices, discovery_info=None):
    """Set up the BMW sensors."""
    accounts = hass.data[BMW_DOMAIN]
    _LOGGER.debug('Found BMW accounts: %s',
                  ', '.join([a.name for a in accounts]))
    devices = []
    for account in accounts:
        for vehicle in account.account.vehicles:
            for key, value in sorted(SENSOR_TYPES.items()):
                device = BMWConnectedDriveSensor(account, vehicle, key, value[0], value[1])
                devices.append(device)
    add_devices(devices, True)


class BMWConnectedDriveSensor(Entity):
    """Representation of a BMW vehicle binary sensor."""

    def __init__(self, account, vehicle, attribute: str, sensor_name, device_class):
        """Constructor."""
        self._account = account
        self._vehicle = vehicle
        self._attribute = attribute
        self._name = sensor_name
        self._device_class = device_class
        self._state = None
        self._unit_of_measurement = None

    @property
    def should_poll(self) -> bool:
        """Data update is triggered from BMWConnectedDriveEntity."""
        return False

    @property
    def device_class(self):
        """Return the class of the binary sensor."""
        return self._device_class
    
    @property
    def name(self):
        """Return the name of the binary sensor."""
        return self._name

    @property
    def state(self):
        """Return the state of the binary sensor.
        The return type of this call depends on the attribute that
        is configured.
        """
        return self._state
    
    # @property
    # def is_on(self):
    #     """Return the state of the binary sensor."""
    #     return self._state

    @property
    def unit_of_measurement(self) -> str:
        """Get the unit of measurement."""
        return self._unit_of_measurement

    @property
    def device_state_attributes(self):
        """Return the state attributes of the binary sensor."""
        vehicle_state = self._vehicle.state

        if self._attribute == 'all_lids_closed':
            ### Show all lids and statuses here
            return
        else:
            return {
                'last_update': vehicle_state.timestamp,
                'car': self._vehicle.modelName
            }

    def update(self) -> None:
        """Read new state data from the library."""
        vehicle_state = self._vehicle.state
        #self._state = getattr(vehicle_state, self._attribute)

        # device class opening: On means open, Off means closed
        if self._attribute == 'all_lids_closed':
            _LOGGER.debug("Status of lid: %s", vehicle_state.all_lids_closed)
            self._state = not vehicle_state.all_lids_closed
        if self._attribute == 'all_windows_closed':
            self._state = not vehicle_state.all_windows_closed
        # device class safety: On means unsafe, Off means safe
        if self._attribute == 'door_lock_state': # LOCKED, SECURED, SELECTIVELOCKED, UNLOCKED
            self._state = bool(vehicle_state.door_lock_state in ('UNLOCKED', 'SELECTIVELOCKED'))

        self.schedule_update_ha_state()
    
    @asyncio.coroutine
    def async_added_to_hass(self):
        """Add callback after being added to hass.
        Show latest data after startup.
        """
        self._account.add_update_listener(self.update)
        self.update()

```

**Comment by ChristianKuehnel** [comment]
@gerard33 I just uploaded your code to a new branch on top of my pull request so that I could test and modify it. Looks good to me. I only did some small changes :smile: 
https://github.com/ChristianKuehnel/home-assistant/commit/ce7699d61208bffb9051fc987a1ff8916521f4c4

The results looks like this:
![image](https://user-images.githubusercontent.com/19961352/36387633-c08cfb00-1599-11e8-8258-ba0e96d99098.png)

Is that what you wanted to have?

On second thought having a state "false" is not so nice, so I changed it to "open"/"closed" in another commit:
https://github.com/ChristianKuehnel/home-assistant/commit/d3ff1b36f1cd3853dd86d4534ac04552ea12560b

Concerning the `NoEntitySpecifiedError` error: I could resolve it be changing `add_devices(devices, True)` to `add_devices(devices)`. I'm not really sure where this problem comes from, but I had the same issue with my sensor component.

My branch is here: https://github.com/home-assistant/home-assistant/compare/dev...ChristianKuehnel:bimmer_binary
Feel free to fork it or only copy the file or do what helps you the most.

**Comment by gerard33** [comment]
That’s exactly what I wanted to achieve :)

I fully agree with the open/closed state. Strange thing is that on my old version that used to work automatically by using device classes. Will have another look at it, but your solution also works.

Will copy the updated code from your github this evening :)

**Comment by gerard33** [comment]
I have fixed the open/closed state by using device classes. Had to do with importing the right parts.
This is how it looks right now. Will make a PR for this version on your branch.

Next on the list can be to add the extra attributes from the list in the first post to the bimmer module.

![screenshot_3](https://user-images.githubusercontent.com/11230573/36398837-4d863ace-15c9-11e8-950b-3ebb17c9e259.png)
![screenshot_4](https://user-images.githubusercontent.com/11230573/36398839-4eed1270-15c9-11e8-8670-8d594c23fd86.png)
_Forget about the False status in the history, that is still part of the previous solution._

**Comment by gerard33** [comment]
And this is the latest version.

```py
"""
Reads vehicle status from BMW connected drive portal.

For more details about this platform, please refer to the documentation at
https://home-assistant.io/components/binary_sensor.bmw_connected_drive/
"""
import logging
import asyncio

from custom_components.bmw_connected_drive import DOMAIN as BMW_DOMAIN
#from homeassistant.components.bmw_connected_drive import DOMAIN as BMW_DOMAIN
from homeassistant.components.binary_sensor import (
    BinarySensorDevice, DEVICE_CLASSES_SCHEMA)
from homeassistant.const import (CONF_DEVICE_CLASS)

DEPENDENCIES = ['bmw_connected_drive']

_LOGGER = logging.getLogger(__name__)

SENSOR_TYPES = {
    'all_lids_closed': ['Doors', 'opening'],
    'all_windows_closed': ['Windows', 'opening'],
    'door_lock_state': ['Door lock state', 'safety']
}


def setup_platform(hass, config, add_devices, discovery_info=None):
    """Set up the BMW sensors."""
    accounts = hass.data[BMW_DOMAIN]
    _LOGGER.debug('Found BMW accounts: %s',
                  ', '.join([a.name for a in accounts]))
    devices = []
    for account in accounts:
        for vehicle in account.account.vehicles:
            for key, value in sorted(SENSOR_TYPES.items()):
                device = BMWConnectedDriveSensor(account, vehicle, key,
                                                 value[0], value[1])
                devices.append(device)
    add_devices(devices)


class BMWConnectedDriveSensor(BinarySensorDevice):
    """Representation of a BMW vehicle binary sensor."""

    def __init__(self, account, vehicle, attribute: str, sensor_name,
                 device_class):
        """Constructor."""
        self._account = account
        self._vehicle = vehicle
        self._attribute = attribute
        self._name = sensor_name
        self._device_class = device_class
        self._state = None
        self._unit_of_measurement = None

    @property
    def should_poll(self) -> bool:
        """Data update is triggered from BMWConnectedDriveEntity."""
        return False

    @property
    def name(self):
        """Return the name of the binary sensor."""
        return self._name

    @property
    def device_class(self):
        """Return the class of the binary sensor."""
        return self._device_class

    @property
    def is_on(self):
        """Return the state of the binary sensor."""
        return self._state

    @property
    def unit_of_measurement(self) -> str:
        """Get the unit of measurement."""
        return self._unit_of_measurement

    @property
    def device_state_attributes(self):
        """Return the state attributes of the binary sensor."""
        vehicle_state = self._vehicle.state
        result = {
            'last_update': vehicle_state.timestamp,
            'car': self._vehicle.modelName
        }

        if self._attribute == 'all_lids_closed':
            for lid in vehicle_state.lids:
                result[lid.name] = lid.state.value
        
        if self._attribute == 'all_windows_closed':
            for lid in vehicle_state.windows:
                result[lid.name] = lid.state.value
        
        if self._attribute == 'door_lock_state':
            result['door_lock_state'] = vehicle_state.door_lock_state.value

        return result

    def update(self):
        """Read new state data from the library."""
        vehicle_state = self._vehicle.state

        # device class opening: On means open, Off means closed
        if self._attribute == 'all_lids_closed':
            _LOGGER.debug("Status of lid: %s", vehicle_state.all_lids_closed)
            self._state = not vehicle_state.all_lids_closed
        if self._attribute == 'all_windows_closed':
            self._state = not vehicle_state.all_windows_closed
        # device class safety: On means unsafe, Off means safe
        if self._attribute == 'door_lock_state':
            # LOCKED, SECURED, SELECTIVELOCKED, UNLOCKED
            self._state = bool(vehicle_state.door_lock_state.value
                               in ('SELECTIVELOCKED', 'UNLOCKED'))

        self.schedule_update_ha_state()

    @asyncio.coroutine
    def async_added_to_hass(self):
        """Add callback after being added to hass.
        Show latest data after startup.
        """
        self._account.add_update_listener(self.update)
        yield from self.hass.async_add_job(self.update)

```

**Comment by ChristianKuehnel** [comment]
@gerard33 just updated the code and it's working for my setup. nice work :+1:

**Comment by gerard33** [comment]
Doors, windows and door lock state will be available in the next HA release https://github.com/home-assistant/home-assistant/pull/12591.
Other binary sensors will be added in next releases.

**Comment by robbz23** [comment]
@gerard33 Can you include lastChargingEndResult when you do the binary sensors for electric cars.  I could probably do it this weekend if you can give me an example to follow.  I actually had an issue this week where my car blew the fuse in the house and I came out in the morning to a dead battery.  Its disappointing that the bmw app can notify me that charging failed.

**Comment by gerard33** [comment]
I will add that and make it available in the custom component so you can already try it before it’s part of an actual HA release.

**Comment by m1n3rva** [comment]
Hey @gerard33, happy Easter :rabbit::egg:!

my idea was to use the property `vehicle.drive_train_attributes` to find out which drive train related attributes are available: 
https://github.com/m1n3rva/bimmer_connected/blob/92773affc3ce5cb36734dc6a86f3b1f7ef412592/bimmer_connected/vehicle.py#L86

This function already figures out which attributes are available for which vehicle. This is based on the data I've seen so far. This function is already using `has_hv_battery` and `has_internal_combustion_engine` internally.

So my plan would be something like for HASS:
```python
def setup_platform(hass, config, add_devices, discovery_info=None):
    """Set up the BMW sensors."""
    accounts = hass.data[BMW_DOMAIN]
    _LOGGER.debug('Found BMW accounts: %s',
                  ', '.join([a.name for a in accounts]))
    devices = []
    for account in accounts:
        for vehicle in account.account.vehicles:
            for attribute_name in vehicle.drive_train_attributes:  
                    device = BMWConnectedDriveSensor(account, vehicle, key, attribute_name)
                    devices.append(device)
    add_devices(devices, True)
```
In the sensor you can then use `get_attr(vehicle.state, attribute_name)` to get the value for the attribute. 

In `BMWConnectedDriveSensor` you then need to figure out which unit of measurement each attribute has. Or we could add a feature to bimmer_connected, that gives you the unit_of_measurement for the different attributes. Something like:

``` python
def get_unit_of_measurement(attribute):
    if attribute == 'mileage':
        return 'km'
   elif attribute == 'reamaining_fuel':
        return 'l' 
  ...
```

Or we change the attributes so that they return a tuple: (value, unit_of_measurement)

**Comment by gerard33** [comment]
Hi @m1n3rva, the same for you!

Thanks for your extensive explanation.

I saw the `vehicle.drive_train_attributes` you have added and will use that for the sensors.

For the binary sensor I only want to add a `charging` and `connected` sensor.
Based on your example it was just changing `if account.vehicle.has_hv_battery:` to `if vehicle.has_hv_battery:` :ok_hand:

**Comment by gerard33** [comment]
I have added the above to the binary sensors on my custom component and Vasaru successfully tested this with his hybrid car. So that is something I will add to the next PR.

@robbz23 Can you check [this version](https://github.com/gerard33/home-assistant/tree/master/bmw_connecteddrive) as well? I have also added the `lastChargingEndResult` to the charging status sensor.

![af0174ababe4cf9777c619dbf20a5202f219346c_1_331x500](https://user-images.githubusercontent.com/11230573/38390694-567e4028-3922-11e8-9f0e-59d3cea1e66e.png)

**Comment by robbz23** [comment]
It looks really good.  I see in states that the last_charging_end_result shows up so I cant wait to get automating that.  Is there anyway we can get more information about range though?  like remainingRangeElectric and max range electric (this value varies depending on driving style and weather etc)?  I want to make a bar graph from these two to show in the gui.

![image](https://user-images.githubusercontent.com/5486769/38395045-3b003a54-3931-11e8-925b-230669d1cc38.png)

**Comment by gerard33** [comment]
I have just added extra sensors for electric/hybrid cars. More info here https://github.com/m1n3rva/bimmer_connected/issues/16#comment-379090810.
So that’s ready for testing.

**Comment by m1n3rva** [comment]
@gerard33 the list of attributes is now quite impressive :+1: :smile: 

I'm not sure about the switches: They are not really switches in the Home Assistant, because you cannot switch on/off the AC or the lights or the forn. You can just switch it on and they will turn of automatically. And we do not have the current state of the AC of the vehicle. So I guess it would be better to offer them as services instead, as proposed in  https://github.com/home-assistant/home-assistant/pull/13497 .

The lock really is a proper lock: you can lock/unlock the car and we can query the state of the car.

If someone wants to have it clickable :computer_mouse: on the UI :computer: , he would have to use a script or automation for this.

**Comment by gerard33** [comment]
I fully agree. The switches are not necessary anymore after the PR with the services.

I will add the new binary sensors into a HA PR and afterwards close this ticket.
