### ISSUE TITLE
Missing beRemainingRangeFuel attribute

### ISSUE THREAD

**Issue by kstaniek** [ChristianKuehnel/bimmer_connected#30]
I'm facing an issue getting the vehicle state.
```
Traceback (most recent call last):
  File "/config/deps/lib/python3.6/site-packages/bimmer_connected/state.py", line 44, in _func_wrapper
    return func(self, *args, **kwargs)
  File "/config/deps/lib/python3.6/site-packages/bimmer_connected/state.py", line 141, in remaining_range_fuel
    return float(self._attributes['beRemainingRangeFuel'])
KeyError: 'beRemainingRangeFuel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/bmw_connected_drive.py", line 98, in update
    listener()
  File "/usr/lib/python3.6/site-packages/homeassistant/components/sensor/bmw_connected_drive.py", line 81, in update
    self._state = getattr(vehicle_state, self._attribute)
  File "/config/deps/lib/python3.6/site-packages/bimmer_connected/state.py", line 46, in _func_wrapper
    raise ValueError('No data available!')
ValueError: No data available!
```

It seems that for my car the beRemainingRangeFuel is missing.

This is what I'm getting:

```
{
  "attributesMap" : {
    "DCS_CCH_Ongoing " : null,
    "unitOfElectricConsumption" : "kWh/100km",
    "mileage" : "xxxxx",
    "head_unit_pu_software" : "07/14",
    "gps_lat" : "xxxxxx",
    "head_unit" : "NBT",
    "DCS_CCH_Activation" : null,
    "condition_based_services" : "00001,OVERDUE,12.2018,-500,453,19,24;00100,OVERDUE,12.2018,-500,453,38,48;00002,PENDING,,140,,36,;00003,OK,4.2019,,573,,24;00032,OK,4.2019,,573,,;00033,OK,4.2019,,573,,",
    "vehicle_tracking" : "1",
    "remaining_fuel" : "66",
    "lastUpdateReason" : "Error",
    "gps_lng" : "xxxxxxx",
    "unitOfCombustionConsumption" : "l/100km",
    "unitOfEnergy" : "kWh",
    "unitOfLength" : "km"
  },
  "vehicleMessages" : {
    "ccmMessages" : [ ],
    "cbsMessages" : [ {
      "description" : "Minął termin przeglądu! Proszę jak najszybciej ustalić termin ze swoim serwisem.",
      "text" : "Olej silnikowy",
      "id" : 1,
      "status" : "OVERDUE",
      "messageType" : "CBS",
      "date" : "12.2018",
      "unitOfLengthRemaining" : "-500"
    }, {
      "description" : "Minął termin kontroli wzrokowej! Proszę ustalić termin ze swoim serwisem.",
      "text" : "Kontrola pojazdu",
      "id" : 100,
      "status" : "OVERDUE",
      "messageType" : "CBS",
      "date" : "12.2018",
      "unitOfLengthRemaining" : "-500"
    }, {
      "description" : "Zbliża się termin wymiany. Proszę ustalić termin ze swoim serwisem.",
      "text" : "Okładz. hamulc. przód",
      "id" : 2,
      "status" : "PENDING",
      "messageType" : "CBS",
      "date" : "",
      "unitOfLengthRemaining" : "140"
    }, {
      "description" : "Następna wymiana najpóźniej w podanym terminie.",
      "text" : "Płyn hamulcowy",
      "id" : 3,
      "status" : "OK",
      "messageType" : "CBS",
      "date" : "4.2019",
      "unitOfLengthRemaining" : ""
    }, {
      "description" : "Następne obowiązkowe badanie techniczne pojazdu w podanym terminie.",
      "text" : "§ Badan. techn. pojazdu",
      "id" : 32,
      "status" : "OK",
      "messageType" : "CBS",
      "date" : "4.2019",
      "unitOfLengthRemaining" : ""
    }, {
      "description" : "Następne obowiązkowe badanie emisji spalin najpóźniej w podanym terminie.",
      "text" : "§ Badanie emisji spalin",
      "id" : 33,
      "status" : "OK",
      "messageType" : "CBS",
      "date" : "4.2019",
      "unitOfLengthRemaining" : ""
    } ]
  }
}
```

**Comment by gerard33** [comment]
@ChristianKuehnel 
Maybe change these parts
```py
self._attributes['beRemainingRangeFuel']
```
to
```py
self._attributes.get('beRemainingRangeFuel')
```
so None is returned when key is not available.
Because in this case the `backend_parameter()` doesn't raise an error as `self._attributes` contains data.

**Comment by ChristianKuehnel** [comment]
@kstaniek thx for the bug report!

Yes, it seems NBT does not provide this kind of data. For the short term:
Whenever an attribute is missing, I'm returning None instead of an Exception.

@gerard33 For the medium term we probably need to figure out, which head units provides which attributes and then configure the sensors in HomeAssistant accordingly. So only create the sensors that are avaiable for this head unit. This somehow sounds like a nightmare in variant handling... :unamused:
